config/routes.rb
MsFixMeApp::Application.routes.draw do

  get "pages/show_page"

  match '/' => 'home#home'
  match '/products/:url_segment' => 'products#show'
  match '/categories/:url_segment' => 'categories#show'
  match '/administration/users/sign_up' => 'pages#show_page'
  namespace :administration do
    match '/' => 'home#home'
    resources :categories do
      member do
        post :archive
        post :publish
        post :remove
        post :unarchive
        post :undelete
      end
    end

    resources :pages

    resources :products do
      member do
        post :archive
        post :publish
        post :remove
        post :unarchive
        post :undelete
      end
      collection do
        put :archive
      end
    end

    resources :variants
    
    devise_for :users, :controllers => { :sessions => "administration/sessions" }
  end

  match "*a", :to => "pages#show_page"

end

app/models/variant.rb
class Variant < ActiveRecord::Base
  attr_accessible :bay, :description, :price, :product_id, :sku, :stock_level_reserved, :stock_level_total, :weight_in_grams

  belongs_to :product

  def buyable?
  	stock_level_available > 0
  end

  def stock_level_available
  	stock_level_total - stock_level_reserved
  end

end

app/controllers/administration/administration_controller.rb
class Administration::AdministrationController < ApplicationController

  before_filter :authenticate_administration_user!

	layout 'administration/application'

	def archive
		@model = params[:klass].constantize.find(params[:id])

		@model.archive!

		redirect_to :back
	end

	def publish
		@model = params[:klass].constantize.find(params[:id])

		@model.publish!

		redirect_to :back
	end

	def remove
		@model = params[:klass].constantize.find(params[:id])

		@model.remove!

		redirect_to :back
	end

	def unarchive
		@model = params[:klass].constantize.find(params[:id])

		@model.unarchive!

		redirect_to :back
	end

	def undelete
		@model = params[:klass].constantize.find(params[:id])

		@model.undelete!

		redirect_to :back
	end
	
end

app/controllers/administration/categories_controller.rb
class Administration::CategoriesController < Administration::AdministrationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.published

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to administration_category_path(@category), notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])
    # Make sure to remove the picture
    params[:category][:picture].nil? ? @category.update_attribute( :picture, nil) : ""
    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to administration_category_path(@category), notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to administration_categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/administration/home_controller.rb
class Administration::HomeController < Administration::AdministrationController

	def home
    @page = Page.where(:name => "home").first
    if @page
      render :template => 'pages/show_page'
    else
      
    end
	end
	
end	

app/controllers/administration/pages_controller.rb
class Administration::PagesController < Administration::AdministrationController
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to administration_page_path(@page), notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to administration_page_path(@page), notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to administration_pages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/administration/products_controller.rb
class Administration::ProductsController < Administration::AdministrationController
  # GET /products
  # GET /products.json
  def index
    if params[:status]
      @products = Product.where(published_status: params[:status].to_i)
    else
      @products = Product.published
    end
    respond_to do |format|
      format.html # index.html.erb
      format.js # index.html.erb    
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to administration_product_path(@product), notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])
    # Make sure to remove the picture
    params[:product][:picture].nil? ? @product.update_attribute( :picture, nil) : ""
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to administration_product_path(@product), notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to administration_products_url }
      format.json { head :no_content }
    end
  end
  
  def archive
    Product.update_all( "published_status = 4", :id => params[:product_ids])
    redirect_to :back
  end
    
end

app/controllers/administration/registrations_controller.rb
class Administration::RegistrationsController < Devise::RegistrationsController
  
  layout "administration/application"
  
end

app/controllers/administration/sessions_controller.rb
class Administration::SessionsController < Devise::SessionsController
  
  layout "administration/application"

end

app/controllers/administration/variants_controller.rb
class Administration::VariantsController < Administration::AdministrationController
  # GET /variants
  # GET /variants.json
  def index
    @variants = Variant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @variants }
    end
  end

  # GET /variants/1
  # GET /variants/1.json
  def show
    @variant = Variant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @variant }
    end
  end

  # GET /variants/new
  # GET /variants/new.json
  def new
    @variant = Variant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @variant }
    end
  end

  # GET /variants/1/edit
  def edit
    @variant = Variant.find(params[:id])
  end

  # POST /variants
  # POST /variants.json
  def create
    @variant = Variant.new(params[:variant])

    respond_to do |format|
      if @variant.save
        format.html { redirect_to administration_variant_path(@variant), notice: 'Variant was successfully created.' }
        format.json { render json: @variant, status: :created, location: @variant }
      else
        format.html { render action: "new" }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /variants/1
  # PUT /variants/1.json
  def update
    @variant = Variant.find(params[:id])

    respond_to do |format|
      if @variant.update_attributes(params[:variant])
        format.html { redirect_to @variant, notice: 'Variant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variants/1
  # DELETE /variants/1.json
  def destroy
    @variant = Variant.find(params[:id])
    @variant.destroy

    respond_to do |format|
      format.html { redirect_to administration_variants_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/variants_controller.rb
class VariantsController < ShowController
  
end

app/helpers/administration/administration_helper.rb
module Administration::AdministrationHelper

	def category_link(category)
		return '' unless category

		link_to(category.name, administration_category_path(category))
	end

	def published_status(i)
		ActsAsPublishable::STATUS_NAMES[i]
	end
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/administration/variants/_form.html.erb
<%= form_for(@variant, :url => administration_variants_path) do |f| %>
  <% if @variant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@variant.errors.count, "error") %> prohibited this variant from being saved:</h2>

      <ul>
      <% @variant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sku %>
    <%= f.text_field :sku %>
  </div>
  <div class="field">
    <%= f.label :product_id %>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :weight_in_grams %>
    <%= f.number_field :weight_in_grams %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :bay %>
    <%= f.text_field :bay %>
  </div>
  <div class="field">
    <%= f.label :stock_level_total %>
    <%= f.number_field :stock_level_total %>
  </div>
  <div class="field">
    <%= f.label :stock_level_reserved %>
    <%= f.number_field :stock_level_reserved %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/administration/variants/edit.html.erb
<h1>Editing variant</h1>

<%= render 'form' %>

<%= link_to 'Show', administration_variant_path(@variant) %> |
<%= link_to 'Back', administration_variants_path %>

app/views/administration/variants/index.html.erb
<h1>Listing variants</h1>

<table>
  <tr>
    <th>Sku</th>
    <th>Product</th>
    <th>Price</th>
    <th>Weight in grams</th>
    <th>Description</th>
    <th>Bay</th>
    <th>Stock level total</th>
    <th>Stock level reserved</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @variants.each do |variant| %>
  <tr>
    <td><%= variant.sku %></td>
    <td><%= variant.product_id %></td>
    <td><%= variant.price %></td>
    <td><%= variant.weight_in_grams %></td>
    <td><%= variant.description %></td>
    <td><%= variant.bay %></td>
    <td><%= variant.stock_level_total %></td>
    <td><%= variant.stock_level_reserved %></td>
    <td><%= link_to 'Show', administration_variant_path(variant) %></td>
    <td><%= link_to 'Edit', edit_administration_variant_path(variant) %></td>
    <td><%= link_to 'Destroy', administration_variant_path(variant), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Variant', new_administration_variant_path %>

app/views/administration/variants/new.html.erb
<h1>New variant</h1>

<%= render 'form' %>

<%= link_to 'Back', administration_variants_path %>

app/views/administration/variants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sku:</b>
  <%= @variant.sku %>
</p>

<p>
  <b>Product:</b>
  <%= @variant.product_id %>
</p>

<p>
  <b>Price:</b>
  <%= @variant.price %>
</p>

<p>
  <b>Weight in grams:</b>
  <%= @variant.weight_in_grams %>
</p>

<p>
  <b>Description:</b>
  <%= @variant.description %>
</p>

<p>
  <b>Bay:</b>
  <%= @variant.bay %>
</p>

<p>
  <b>Stock level total:</b>
  <%= @variant.stock_level_total %>
</p>

<p>
  <b>Stock level reserved:</b>
  <%= @variant.stock_level_reserved %>
</p>


<%= link_to 'Edit', edit_administration_variant_path(@variant) %> |
<%= link_to 'Back', administration_variants_path %>